# Generated by Django 5.2.4 on 2025-07-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='type',
        ),
    ]
