# Generated by Django 5.2.4 on 2025-07-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contant_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
