# Generated by Django 5.2.4 on 2025-07-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_contant_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='contant_no',
            new_name='contact_number',
        ),
    ]
