# Generated by Django 5.2.4 on 2025-07-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_uploadedfile_shop_shop_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
