# Generated by Django 5.2.4 on 2025-07-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_shop_code_alter_shop_shop_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
