# Generated by Django 5.2.4 on 2025-07-22 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_menucategory_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='shop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_cate', to='api.shop'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_image', to='api.uploadedfile')),
                ('menu_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_category', to='api.shop')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_menu', to='api.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
