# Generated by Django 5.2.4 on 2025-07-27 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_menurate'),
    ]

    operations = [
        migrations.AddField(
            model_name='menurate',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menurate',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_rate_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
