# Generated by Django 5.2.4 on 2025-07-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_menurate_comment_alter_menurate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menurate',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_rate_order', to='api.order'),
            preserve_default=False,
        ),
    ]
