# Generated by Django 5.2.4 on 2025-07-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('organization_admin', 'Organization Admin'), ('shop_admin', 'Shop Admin'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
