# Generated by Django 5.2.4 on 2025-08-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('table_number', models.CharField(max_length=20)),
                ('number_set', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinning_table_shop', to='api.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
