# Generated by Django 5.2.4 on 2025-08-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_dinningtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinningtable',
            name='shop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinning_table_shop', to='api.shop'),
        ),
    ]
