# Generated by Django 5.2.4 on 2025-08-01 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_dinningtable_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='table_number_order', to='api.dinningtable'),
            preserve_default=False,
        ),
    ]
