# Generated by Django 5.2.4 on 2025-08-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_order_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='preparation_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
