# Generated by Django 5.2.4 on 2025-09-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_order_shop_remove_order_table_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
