# Generated by Django 5.2.4 on 2025-09-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_message_room_remove_message_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='shop',
        ),
    ]
