# Generated by Django 5.2.4 on 2025-09-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_menu_image_remove_menu_menu_category_and_more'),
        ('orders', '0002_alter_menurate_menu_alter_orderitem_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
