# Generated by Django 5.2.4 on 2025-09-23 14:05

import django.db.models.deletion
from django.db import migrations, models


def copy_api_menu_to_menu(apps, schema_editor):
    # Copy MenuCategory
    with schema_editor.connection.cursor() as cursor:
        # Create destination tables already exist at this point
        # Copy menucategory
        cursor.execute(
            """
            INSERT INTO menu_menucategory (id, create_date, update_date, name, description, image_id, shop_id)
            SELECT id, create_date, update_date, name, description, image_id, shop_id
            FROM api_menucategory
            ON CONFLICT (id) DO NOTHING
            """
        )
        # Copy menu
        cursor.execute(
            """
            INSERT INTO menu_menu (id, create_date, update_date, name, description, image_id, shop_id, menu_category_id, price, is_active, preparation_time)
            SELECT id, create_date, update_date, name, description, image_id, shop_id, menu_category_id, price, is_active, preparation_time
            FROM api_menu
            ON CONFLICT (id) DO NOTHING
            """
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0035_remove_menu_image_remove_menu_menu_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_image', to='api.uploadedfile')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_cate', to='api.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('preparation_time', models.IntegerField()),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_image', to='api.uploadedfile')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_menu', to='api.shop')),
                ('menu_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_category', to='menu.menucategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(copy_api_menu_to_menu, migrations.RunPython.noop),
    ]
