# Generated by Django 5.2.4 on 2025-09-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_delete_menu_delete_menucategory'),
        ('menu', '0002_allow_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_category', to='menu.menucategory'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='shop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_cate', to='api.shop'),
        ),
    ]
