# Generated by Django 5.2.4 on 2025-09-23 14:05

import django.db.models.deletion
from django.db import migrations, models


def copy_api_menu_into_menu(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        # Copy MenuCategory basic fields (without image/shop which may be removed already)
        cursor.execute(
            """
            INSERT INTO menu_menucategory (id, create_date, update_date, name, description)
            SELECT id, create_date, update_date, name, description
            FROM api_menucategory
            ON CONFLICT (id) DO NOTHING
            """
        )
        # Copy Menu records (without image/shop/menu_category which may be removed already)
        cursor.execute(
            """
            INSERT INTO menu_menu (id, create_date, update_date, name, description, price, is_active, preparation_time)
            SELECT id, create_date, update_date, name, description, price, is_active, preparation_time
            FROM api_menu
            ON CONFLICT (id) DO NOTHING
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_allow_nulls'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_api_menu_into_menu, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='menurate',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_rate', to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_order_items', to='menu.menu'),
        ),
    ]
